import React, { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import toast from 'react-hot-toast';
import { apiService } from '../services/api';

export default function Settings() {
  const { data: health, refetch } = useQuery({ queryKey: ['health'], queryFn: apiService.detailedHealth, refetchInterval: 30000 });
  const [llmModel, setLlmModel] = useState('llama3.2');
  const [maxAgents, setMaxAgents] = useState(10000);
  const [mutationRate, setMutationRate] = useState(0.1);
  return <div className="space-y-6"><div><h1 className="text-2xl font-bold text-gray-900 dark:text-white">Configurações</h1><p className="text-gray-500 dark:text-gray-400 mt-1">Configure o comportamento do sistema</p></div><div className="grid grid-cols-1 lg:grid-cols-2 gap-6"><div className="card"><h3 className="text-lg font-semibold mb-4">Status do Sistema</h3><div className="space-y-3"><div className="flex justify-between"><span className="text-gray-500">Status:</span><span className={`font-medium ${health?.status === 'running' ? 'text-green-600' : 'text-yellow-600'}`}>{health?.status || 'Desconhecido'}</span></div><div className="flex justify-between"><span className="text-gray-500">LLM Local:</span><span className={health?.llm_connected ? 'text-green-600' : 'text-red-600'}>{health?.llm_connected ? 'Conectado' : 'Offline'}</span></div><div className="flex justify-between"><span className="text-gray-500">Uptime:</span><span>{Math.floor((health?.uptime || 0) / 3600)} horas</span></div><div className="flex justify-between"><span className="text-gray-500">Agentes ativos:</span><span>{health?.simulation?.active_agents || 0}</span></div></div></div><div className="card"><h3 className="text-lg font-semibold mb-4">Configurações da LLM</h3><div className="space-y-4"><div><label className="block text-sm font-medium mb-1">Modelo</label><input type="text" value={llmModel} onChange={(e)=>setLlmModel(e.target.value)} className="w-full px-3 py-2 border rounded-lg dark:bg-gray-700 dark:border-gray-600" /><p className="text-xs text-gray-500 mt-1">Modelo Ollama (ex: llama3.2, mistral, phi3)</p></div></div></div><div className="card"><h3 className="text-lg font-semibold mb-4">Configurações dos Agentes</h3><div className="space-y-4"><div><label className="block text-sm font-medium mb-1">Máximo de Agentes</label><input type="number" value={maxAgents} onChange={(e)=>setMaxAgents(parseInt(e.target.value || '0', 10))} className="w-full px-3 py-2 border rounded-lg dark:bg-gray-700 dark:border-gray-600" /></div><div><label className="block text-sm font-medium mb-1">Taxa de Mutação</label><input type="range" min="0" max="0.5" step="0.01" value={mutationRate} onChange={(e)=>setMutationRate(parseFloat(e.target.value))} className="w-full" /><div className="flex justify-between text-xs text-gray-500"><span>0%</span><span>{Math.round(mutationRate * 100)}%</span><span>50%</span></div></div></div></div><div className="card"><h3 className="text-lg font-semibold mb-4">Ações</h3><div className="space-y-3"><button onClick={() => toast.success('Configurações salvas! Reinicie o sistema para aplicar.')} className="w-full btn-primary">Salvar Configurações</button><button onClick={() => refetch()} className="w-full btn-secondary">Verificar Conexões</button></div></div></div></div>;
}
