import { Prediction, Stats } from '../../services/api';

interface SimulationViewProps { prediction?: Prediction & { status?: string }; stats?: Stats; }

export default function SimulationView({ prediction, stats }: SimulationViewProps) {
  const simulation = stats?.simulation || {} as Stats['simulation'];
  const generation = stats?.generation || {} as Stats['generation'];
  return <div className="card"><h3 className="text-lg font-semibold mb-4">Estado da Simulação</h3><div className="grid grid-cols-2 gap-4 mb-6"><div className="text-center p-3 bg-gray-50 dark:bg-gray-700 rounded-lg"><p className="text-sm text-gray-500">Precisão Atual</p><p className="text-2xl font-bold text-primary-600">{simulation.accuracy?.toFixed(1) || 0}%</p></div><div className="text-center p-3 bg-gray-50 dark:bg-gray-700 rounded-lg"><p className="text-sm text-gray-500">Agentes</p><p className="text-2xl font-bold">{simulation.active_agents || 0} / {generation.total_agents || 0}</p></div></div>{prediction && prediction.status !== 'no_prediction' ? <div className="mt-4 p-4 bg-gray-50 dark:bg-gray-700 rounded-lg"><p className="text-sm text-gray-500 mb-2">Última Previsão</p><div className="flex items-center justify-between"><span className={`text-2xl font-bold ${prediction.prediction === 'BANKER' ? 'text-banker' : 'text-player'}`}>{prediction.prediction}</span><span className="text-lg">{prediction.confidence}% confiança</span></div><div className="mt-2 h-2 bg-gray-200 rounded-full overflow-hidden"><div className={`h-full ${prediction.prediction === 'BANKER' ? 'bg-banker' : 'bg-player'}`} style={{ width: `${prediction.confidence}%` }} /></div><p className="text-xs text-gray-400 mt-2">{prediction.agents_active} agentes votaram</p></div> : <div className="text-center text-gray-400 py-8">Aguardando previsões...</div>}<div className="mt-4 text-sm text-gray-500"><div className="flex justify-between"><span>Rodadas no histórico:</span><span>{simulation.history_size || 0}</span></div><div className="flex justify-between mt-1"><span>Previsões realizadas:</span><span>{simulation.predictions_made || 0}</span></div><div className="flex justify-between mt-1"><span>Geração neuroevolução:</span><span>{simulation.neuroevolution?.generation || 0}</span></div></div></div>;
}
